# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 807733a86d6471c2390e4ce2235dbb67c6ee04625589094e9b078c96b0996a7b2e804447dcd54093ac52807e87096e64046bbfcd5f2359021da731951d08b80c

test:
  secret_key_base: e78a8da1fe539c35afe37f76bbca35c91c1cab794072662db57482439b6378c24c64344fe41f1b698ad89debcbc71ae93559c8a21ad9d19194d533c38456f374

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
